spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product-service/v3/api-docs/**, /api/v1/products/**
              filters:
                - RewritePath=/product-service/(?<remaining>.*), /${remaining}
            - id: category-route
              uri: lb://CATEGORY-SERVICE
              predicates:
                - Path=/category-service/v3/api-docs/**, /api/v1/categories/**
              filters:
                - RewritePath=/category-service/(?<remaining>.*), /${remaining}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
springdoc:
  swagger-ui:
    urls:
      - name: Product service
        url: /product-service/v3/api-docs
      - name: Category-service
        url: /category-service/v3/api-docs


