spring:
  application:
    name: category-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 8081
