spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
    wait-time-in-ms-when-sync-empty: 0
server:
  port: 8761
